apiVersion: redis.operator.io/v1alpha1
kind: RedisFailover
metadata:
  name: my-redis
spec:
  replicas: 3
  sentinelReplicas: 3
  backup:
    enabled: true
    schedule: "@daily"
    retention: 7
    s3:
      bucket: "my-redis-backups"
      endpoint: "s3.amazonaws.com"
      accessKeySecret:
        name: "s3-credentials"
        key: "access-key"
      secretKeySecret:
        name: "s3-credentials"
        key: "secret-key"
EOF

# Create a zip archive
zip -r redis-operator.zip redis-operator

echo "Redis Failover Operator files created and packaged in redis-operator.zip"