apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gitreposcans.gitops.example.com
spec:
  group: gitops.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                repoUrl:
                  type: string
                targetRevision:
                  type: string
                scanInterval:
                  type: string
                pathMappings:
                  type: array
                  items:
                    type: object
                    properties:
                      sourcePath:
                        type: string
                      destinationCluster:
                        type: string
                      destinationNamespace:
                        type: string