apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisfailovers.redis.operator.io
spec:
  group: redis.operator.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 3
                  default: 3
                sentinelReplicas:
                  type: integer
                  minimum: 3
                  default: 3
                backup:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: false
                    schedule:
                      type: string
                      pattern: '^(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every (\d+(ns|us|µs|ms|s|m|h))+)|((((\d+,)+\d+|(\d+(\/|-)\d+)|\*|\d+) ?){5,7}$'
                    retention:
                      type: integer
                      minimum: 1
                      default: 7
                    s3:
                      type: object
                      properties:
                        bucket:
                          type: string
                        endpoint:
                          type: string
                        accessKeySecret:
                          type: object
                          properties:
                            name:
                              type: string
                            key:
                              type: string
                        secretKeySecret:
                          type: object
                          properties:
                            name:
                              type: string
                            key:
                              type: string
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                          default: "100m"
                        memory:
                          type: string
                          default: "100Mi"
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                          default: "500m"
                        memory:
                          type: string
                          default: "500Mi"
  scope: Namespaced
  names:
    plural: redisfailovers
    singular: redisfailover
    kind: RedisFailover
    shortNames: ["rfo"]
