apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-backup-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: db-backup-operator
  template:
    metadata:
      labels:
        control-plane: db-backup-operator
    spec:
      serviceAccountName: db-backup-operator
      securityContext:
        runAsNonRoot: true
      containers:
      - name: manager
        image: db-backup-operator:latest
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
