apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresclusters.postgres.operator.io
spec:
  group: postgres.operator.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                minReplicas:
                  type: integer
                  minimum: 1
                  default: 1
                maxReplicas:
                  type: integer
                  minimum: 1
                  maximum: 10
                  default: 3
                targetQPS:
                  type: integer
                  description: "Queries per second per replica before scaling"
                  default: 1000
                targetLatency:
                  type: integer
                  description: "Target average query latency in ms"
                  default: 50
                scaleUpThreshold:
                  type: integer
                  description: "Percentage above target to trigger scale up"
                  default: 20
                scaleDownThreshold:
                  type: integer
                  description: "Percentage below target to trigger scale down"
                  default: 20
                cooldownPeriod:
                  type: integer
                  description: "Seconds to wait between scaling operations"
                  default: 300
  scope: Namespaced
  names:
    plural: postgresclusters
    singular: postgrescluster
    kind: PostgresCluster
    shortNames: ["pgc"]
