apiVersion: v2
name: gitops-operator
description: A Helm chart for GitOps Automation Operator
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: argo-cd
  version: 5.16.0
  repository: https://argoproj.github.io/argo-helm
  condition: argo-cd.enabled